// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnsOJsQXMSH1ALRc8aL4b1NHdqAWQ855g',
    appId: '1:751505552974:web:bbb1c2f4c46bbead93751f',
    messagingSenderId: '751505552974',
    projectId: 'cucikanlundry',
    authDomain: 'cucikanlundry.firebaseapp.com',
    storageBucket: 'cucikanlundry.firebasestorage.app',
    measurementId: 'G-H8M6P5HM27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMDHZGMXXfa21vAYd7JFQkqriHeJaOySY',
    appId: '1:751505552974:android:2ee54a0fb6a4680193751f',
    messagingSenderId: '751505552974',
    projectId: 'cucikanlundry',
    storageBucket: 'cucikanlundry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC2OzPMW8LMl3RwyLAFLHVb_fzqoE8eu4',
    appId: '1:751505552974:ios:5537c7dfa95687b393751f',
    messagingSenderId: '751505552974',
    projectId: 'cucikanlundry',
    storageBucket: 'cucikanlundry.firebasestorage.app',
    iosBundleId: 'com.example.cucikanLaundry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC2OzPMW8LMl3RwyLAFLHVb_fzqoE8eu4',
    appId: '1:751505552974:ios:5537c7dfa95687b393751f',
    messagingSenderId: '751505552974',
    projectId: 'cucikanlundry',
    storageBucket: 'cucikanlundry.firebasestorage.app',
    iosBundleId: 'com.example.cucikanLaundry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnsOJsQXMSH1ALRc8aL4b1NHdqAWQ855g',
    appId: '1:751505552974:web:cbdc33e035a4b2ea93751f',
    messagingSenderId: '751505552974',
    projectId: 'cucikanlundry',
    authDomain: 'cucikanlundry.firebaseapp.com',
    storageBucket: 'cucikanlundry.firebasestorage.app',
    measurementId: 'G-E34PK0HVC2',
  );
}
